version: '3.8'

services:
  web:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/code
    ports:
      - 8000:80
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env
  test:
    build: .
    command: pytest
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: